### ISSUE TITLE
Fails to call address(this).balance of contract instance

### ISSUE THREAD

**Issue by Mineco1006** [QuarkChain/pyquarkchain#927]
This issue is not nescessarily RPC correlated but rather EVM. It appears that calling the balance property directly from the address of the contract instance, being address(this), returns undefined.
This behaviour can be reproduced with this contract code:
```
pragma solidity ^0.7.4;

contract test {

    function getAddress() public view returns(address) {
        return address(this);
    }
    function getBalance() public view returns(uint256) {
        return address(this).balance;
    }

    function getBalance1() public view returns(uint256) {
        address contractAddress = address(this);
        return contractAddress.balance;
    }
}
```
As the contract balance is 0 the expected return values would be:

```
getBalance(): 0
getBalance1(): 0
```

But it actually returns:

```
getBalance(): undefined
getBalance1(): 0
```

Interestingly directly calling address(this) works fine.

**Comment by Mineco1006** [comment]
I have tried both testnet and mainnet, and I have been using the interface at https://devnet.quarkchain.io/contract and quarkchain-web3.js

**Comment by ping-ke** [comment]
Hi, 

The bug has been fixed, and deploy to devnet, would you try it again?
<img width="610" alt="1630315992(1)" src="https://user-images.githubusercontent.com/14110556/131318910-fdb2bf96-ffc3-4502-9e82-b19f71c19987.png">

**Comment by qizhou** [comment]
Tested and passed on devnet:

![image](https://user-images.githubusercontent.com/2541286/131385950-4b6c81a0-f612-44db-af91-dc9a1d238cc0.png)

**Comment by Mineco1006** [comment]
It still doesn't work. Calling it through quarkchain-web3.js returns undefined, even though the err in the callback is null. 
![image](https://user-images.githubusercontent.com/57864185/131864868-a161a0b1-8358-42dd-8c41-0fe0d7fb7c44.png)

Calling from the devnet page resulted in a status 400 from the backend.
![image](https://user-images.githubusercontent.com/57864185/131865952-ee3a8868-d4c3-4396-982f-c2a3f3ecec5d.png)

I'm still using the devnet's old RPC, it works fine for everything but this special case however, and the mainnet got the same issue.

**Comment by Mineco1006** [comment]
In addition this isn't just an issue with view functions. I coded a non-view function and the transaction fails on the networks end. Here is my new contract:
```
pragma solidity ^0.7.4;

contract test {

    function getAddress() public view returns(address) {
        return address(this);
    }
    function getBalanceView() public view returns(uint256) {
        return address(this).balance;
    }

    function getBalanceView1() public view returns(uint256) {
        address contractAddress = address(this);
        return contractAddress.balance;
    }

    function getBalanceNonView() public returns(uint256) {
        return address(this).balance;
    }

    function getBalanceNonView1() public returns(uint256) {
        address contractAddress = address(this);
        return contractAddress.balance;
    }
}
```

**Comment by qizhou** [comment]
@ninjaahhh @ping-ke Looks like it is related to your rpc.  Do you have any clue?

**Comment by Mineco1006** [comment]
If it was RPC related the transaction wouldn't fail right? I don't know why but it just doesn't seem to work no matter how I try. Somehow everything else works fine, and even the workaround works flawless for me.

**Comment by ping-ke** [comment]
After investigation, we found 
Issue: 
    function with "return address(this).balance;" will return undefined or error, while
    function with "address contractAddress = address(this); return contractAddress.balance;" will return 0

Reason:
    Out EVM do not support opcode for "address(this).balance;" which added to ethereum on Aug 2019. 

Solution:
    Use constantinople as EVM Version when compile contract.
