### ISSUE TITLE
Should not accept failed tx in Metamask

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#929]
Deploy the following contract and send QKC from Metamask to the contract directly.  Since the contract does not have receive/fallback function, any transfer should fail.  However, the Metamask
1, accepts the tx and put it in wait queue
2, after clicking the tx, the tx cannot be found in explorer

The correct behavior should not accept the tx submitted from Metamask.

```
pragma solidity ^0.7.4;

contract test {

    function getAddress() public view returns(address) {
        return address(this);
    }
    function getBalance() public view returns(uint256) {
        return address(this).balance;
    }

    function getBalance1() public view returns(uint256) {
        address contractAddress = address(this);
        return contractAddress.balance;
    }
}
```

**Comment by ping-ke** [comment]
Fixed.

**Comment by qizhou** [comment]
Just checked on the devnet, and now the failed tx will be displayed on testnet.  But I think the problem is not completely solved yet.  The current behavior is that even the tx will be failed, Metamask **does not report the failure** to users - so users will unawarely submit a tx-to-be-failed.  The correct behavior is that Metamask should **warn the user about the failure**, and the user may insist to submit the tx.

**Comment by ping-ke** [comment]
We will return error to metamask when we found failure, but metamask would not should the error, but set the gas limit to 21000. the current behavior is same as ethereum.
